# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79937fc7cc2af56f350d5018eb8480534c264f32fbbca99bbe0cce26081c6e40022b8b13c4a7c76c7f4db586ed127210b49a0790ab5d9e1c54e546e8c404d352

test:
  secret_key_base: 3bad487ba7f31f7e8e52c73f99b88a6390210de1d4012e58fc1071acee1e613bb195963a6c1c77abd7e3bfcd63c86a009997624fc90129ba97c15645b3b5732a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
